# Generated by Django 5.2.5 on 2025-08-21 06:35

import enquiry.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='enquiries/attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='enquiries/images/')),
            ],
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_form',
            field=models.JSONField(validators=[enquiry.validators.EnquirySchemaValidator]),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='enquiries', to='enquiry.enquiryattachment'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='enquiries', to='enquiry.enquiryimage'),
        ),
    ]
