# Generated by Django 5.2.5 on 2025-08-25 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enquiry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquiryattachment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_attachments', to='enquiry.enquiry'),
        ),
        migrations.AddField(
            model_name='enquirycomment',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enquirycomment',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_comments', to='enquiry.enquiry'),
        ),
        migrations.AddField(
            model_name='enquiryimage',
            name='enquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_images', to='enquiry.enquiry'),
        ),
    ]
