# Generated by Django 5.2.5 on 2025-08-21 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_enquiryattachment_enquiryimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='goshe_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='goshe_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enquiryattachment',
            name='file',
            field=models.FileField(upload_to='media/enquiries/attachments/'),
        ),
        migrations.AlterField(
            model_name='enquiryimage',
            name='image',
            field=models.ImageField(upload_to='media/enquiries/images/'),
        ),
    ]
