# Generated by Django 5.2.5 on 2025-08-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_enquiry_goshe_comment_enquiry_goshe_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='goshe_comment',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='goshe_manager',
        ),
    ]
