# Generated by Django 5.2.5 on 2025-08-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_remove_enquiry_goshe_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
