# Generated by Django 5.2.5 on 2025-08-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_enquirycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('pending_support', 'Pending Support From OHSE'), ('in_progress', 'Working In Progress'), ('closed', 'Closed')], default='pending', max_length=50),
        ),
    ]
