# Generated by Django 5.2.5 on 2025-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0008_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_form',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='enquirycomment',
            name='comment',
            field=models.TextField(max_length=1),
        ),
    ]
