# Generated by Django 5.2.5 on 2025-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0009_alter_enquiry_enquiry_form_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquirycomment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
