# Generated by Django 5.2.5 on 2025-08-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0010_alter_enquirycomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_id',
            field=models.CharField(editable=False, max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
