# Generated by Django 5.2.5 on 2025-08-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigation',
            old_name='submitter_id',
            new_name='investigator_id',
        ),
    ]
