# Generated by Django 5.2.5 on 2025-08-25 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigation', '0001_initial'),
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='investigator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='reporting.reportingform'),
        ),
        migrations.AddField(
            model_name='investigationattachment',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_attachments', to='investigation.investigation'),
        ),
        migrations.AddField(
            model_name='investigationcomment',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationcomment',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_comments', to='investigation.investigation'),
        ),
        migrations.AddField(
            model_name='investigationimage',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_images', to='investigation.investigation'),
        ),
    ]
