# Generated by Django 5.2.5 on 2025-08-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_rename_submitter_id_investigation_investigator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investigation',
            old_name='investigator_id',
            new_name='investigator',
        ),
    ]
