# Generated by Django 5.2.5 on 2025-08-22 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0004_investigationcomment'),
        ('reporting', '0006_rename_reportingrejectedcomment_reportingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='report',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='reporting.reportingform'),
            preserve_default=False,
        ),
    ]
