# Generated by Django 5.2.5 on 2025-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0005_investigation_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='investigation_form',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='investigationcomment',
            name='comment',
            field=models.TextField(max_length=500),
        ),
    ]
