# Generated by Django 5.2.5 on 2025-08-21 09:09

import django.db.models.deletion
import reporting.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/reporting/attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/reporting/images/')),
            ],
        ),
        migrations.CreateModel(
            name='ReportingForm',
            fields=[
                ('tracking_no', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('reporting_forms', models.JSONField(validators=[reporting.validators.ReportingFormSchemaValidator])),
                ('incident_status', models.CharField(choices=[('report_pending_approval', 'Report Pending Approval'), ('capa_in_action', 'CAPA In Action'), ('investigation_from_gohse', 'Investigation From GOHSE'), ('closed', 'Closed'), ('rejected_investigation_report', 'Rejected Investigation Report')], default='Pending', max_length=50)),
                ('approver_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='Pending', max_length=50)),
                ('attachments', models.ManyToManyField(blank=True, related_name='reporting', to='reporting.reportingattachment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('images', models.ManyToManyField(blank=True, related_name='reporting', to='reporting.reportingimage')),
            ],
        ),
    ]
