# Generated by Django 5.2.5 on 2025-08-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reporting/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingForm',
            fields=[
                ('tracking_no', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False, unique=True)),
                ('reporting_forms', models.JSONField()),
                ('approver_status', models.CharField(choices=[('pending', 'Pending from Approver'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=50)),
                ('incident_status', models.CharField(blank=True, choices=[('pending_investigation_report', 'Pending Investigation Report'), ('under_investigation', 'Under Investigation'), ('report_pending_approval', 'Report Pending Approval'), ('capa_in_action', 'CAPA In Action'), ('closed', 'Closed'), ('rejected_investigation_report', 'Rejected Investigation Report')], default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reporting/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
