# Generated by Django 5.2.5 on 2025-08-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='incident_status',
            field=models.CharField(blank=True, choices=[('pending_investigation_report', 'Pending Investigation Report'), ('under_investigation', 'Under Investigation'), ('report_pending_approval', 'Report Pending Approval'), ('capa_in_action', 'CAPA In Action'), ('closed', 'Closed'), ('rejected_investigation_report', 'Rejected Investigation Report')], default=None, max_length=50, null=True),
        ),
    ]
