# Generated by Django 5.2.5 on 2025-08-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_reportingattachment_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='approver_status',
            field=models.CharField(choices=[('pending', 'Pending from Approver'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='Pending', max_length=50),
        ),
    ]
