# Generated by Django 5.2.5 on 2025-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingform',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
