# Generated by Django 5.2.5 on 2025-08-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_reportingform_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportingform',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportingform',
            name='incident_category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportingform',
            name='risk_status',
            field=models.CharField(choices=[('Low Risk', 'Low Risk'), ('High Risk', 'High Risk'), ('Critical Risk', 'Critical Risk')], default='null', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
