# Generated by Django 5.2.5 on 2025-08-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_reportingform_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingform',
            name='incident_category',
        ),
        migrations.AlterField(
            model_name='reportingform',
            name='risk_status',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
