# Generated by Django 5.2.5 on 2025-08-22 03:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_rename_approverrejectedcomment_reportingrejectedcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportingRejectedComment',
            new_name='ReportingComment',
        ),
    ]
