# Generated by Django 5.2.5 on 2025-08-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_rename_reportingrejectedcomment_reportingcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='reporting_forms',
            field=models.JSONField(),
        ),
    ]
