# Generated by Django 5.2.5 on 2025-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_alter_reportingform_reporting_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='approver_status',
            field=models.CharField(choices=[('pending', 'Pending from Approver'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='', max_length=50),
        ),
    ]
