# Generated by Django 5.2.5 on 2025-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_alter_reportingform_approver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='approver_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending from Approver'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default=None, max_length=50, null=True),
        ),
    ]
