# Generated by Django 5.2.5 on 2025-08-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_alter_reportingform_approver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportingform',
            name='approver_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending from Approver'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportingform',
            name='incident_status',
            field=models.CharField(blank=True, choices=[('report_pending_approval', 'Report Pending Approval'), ('capa_in_action', 'CAPA In Action'), ('investigation_from_gohse', 'Investigation From GOHSE'), ('closed', 'Closed'), ('rejected_investigation_report', 'Rejected Investigation Report')], default=None, max_length=50, null=True),
        ),
    ]
