# Generated by Django 5.2.5 on 2025-08-25 04:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstAider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, choices=[('menara_sunway', 'Menara Sunway')], default=None, max_length=50, null=True)),
                ('trainer', models.CharField(blank=True, choices=[('john_doe', 'John Doe')], default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorMarshall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('menara_sunway', 'Menara Sunway')], default='menara_sunway', max_length=50)),
                ('trainer', models.CharField(choices=[('john_doe', 'John Doe')], default='john_doe', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('attachment', models.ImageField(upload_to='news/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSHCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, choices=[('menara_sunway', 'Menara Sunway')], default=None, max_length=50, null=True)),
                ('trainer', models.CharField(blank=True, choices=[('john_doe', 'John Doe')], default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('reporter', 'Reporter'), ('approver', 'Approver'), ('investigator', 'Investigator'), ('gohse_team', 'GOHSE Team'), ('gohse_manager', 'GOHSE Manager'), ('observer', 'Observer')], default=None, max_length=50)),
                ('attachment', models.ImageField(upload_to='user_guide/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('user_role', models.CharField(choices=[('reporter', 'Reporter'), ('approver', 'Approver'), ('investigator', 'Investigator'), ('gohse_team', 'GOHSE Team'), ('gohse_manager', 'GOHSE Manager'), ('observer', 'Observer')], default=None, max_length=50)),
                ('business_unit', models.CharField(blank=True, choices=[('group_security', 'Group Security'), ('dcms', 'DCMS'), ('gbmc', 'GBMC'), ('giad', 'GIAD'), ('dsi', 'Digital & Strategic Investment (DSI)'), ('decostyle', 'Decostyle'), ('sunway_leasing_risk', 'Sunway Leasing and Risk'), ('credit_bureau_malaysia_sdn_bhd', 'Credit Bureau Malaysia Sdn Bhd'), ('finance_shared_services_centre_sdn_bhd', 'Finance Shared Services Centre Sdn Bhd'), ('sunway_computer_services_sdn_bhd', 'Sunway Computer Services Sdn Bhd'), ('sunway_money', 'Sunway Money'), ('group_secretarial', 'Group Secretarial'), ('group_accounts', 'Group Accounts'), ('group_legal', 'Group Legal'), ('group_cfo', 'Group CFO'), ('gbmc_18', 'GBMC 18'), ('group_hr', 'Group HR'), ('sunway_travel', 'Sunway Travel'), ('sunway_design', 'Sunway Design'), ('digital_hub', 'Digital Hub'), ('hrssc', 'HRSSC'), ('sunway_pals', 'Sunway Pals'), ('sunway_quantum', 'Sunway Quantum')], default=None, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
