# Generated by Django 5.2.5 on 2025-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('reporter', 'Reporter'), ('approver', 'Approver'), ('investigator', 'Investigator'), ('gohse_team', 'GOHSE Team'), ('gohse_manager', 'GOHSE Manager'), ('observer', 'Observer')], default=None, max_length=50, null=True),
        ),
    ]
