# Generated by Django 5.2.5 on 2025-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstaider',
            name='trainer',
            field=models.CharField(blank=True, choices=[('osh_coordinator', 'OSH Coordinator')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='floormarshall',
            name='trainer',
            field=models.CharField(blank=True, choices=[('osh_coordinator', 'OSH Coordinator')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oshcoordinator',
            name='trainer',
            field=models.CharField(blank=True, choices=[('osh_coordinator', 'OSH Coordinator')], default=None, max_length=50, null=True),
        ),
    ]
